### ISSUE TITLE
[Feature Request] Manually supplying injectables

### ISSUE THREAD

**Issue by romangraef** [allrod5/injectable#36]
Right now it seems impossible to directly supply an injectable instance, except for providing a factory method like so:

```py

a = A()

@injectable_factory(A, singleton=True)
def a_injector():
    return a
```

The alternative would be to move the initialization into the factory, however, sometimes the initialization will run independent from injection discovery, so this isn't applicable. Examples for this would be flask projects with multiple blueprints (i am aware of flask.current_app, but this doesn't always work (e.g. extensions)) and i think providing a single injectable directly would be generally useful, tho i can see why it might go against design thoughts behind injections.

_By submiting an issue I accept this project's
[Code of Conduct](https://github.com/allrod5/injectable/blob/master/CODE_OF_CONDUCT.md). Any issue out of
these guidelines can be deleted at any moment without further explanation._

**Comment by allrod5** [comment]
Hi @romangraef, thanks for your contribution on the matter! I'm having a hard time freeing time for a detailed investigation on this issue. Can you detail how the presented code differs from just:
```python
@injectable_factory(A, singleton=True)
def a_injector():
    return A()
```

As I see it, the singleton directive will render you the very same behaviour of:
```python
a = A()

@injectable_factory(A)
def a_injector():
    return a
```

Also, can you set up a minimal working example with Flask for a better understanding of the issue?

Again, thank you very much for your time on this and I'm really sorry for the lack of time on my part.

**Comment by allrod5** [comment]
@romangraef as I see it the use of factories already got you covered on your intended usage, right? But what you're suggesting would be to enable a simpler way to register injectables that do not need a full factory function? Wouldn't using a lambda suffice?
```python
from injectable import injectable_factory

app = ...

injectable_factory(Flask)(lambda: app)
```

**Comment by romangraef** [comment]
Hey, yes, that would work, in fact, i think we ended up just doing a macro that would just end up doing the lambda method.

**Comment by allrod5** [comment]
Ok, I'll be closing this issue then. Thank you for your thoughts and for helping to make this framework better :heart:
