### ISSUE TITLE
[Bug] inject method signature accepts T instead of Type[T]

### ISSUE THREAD

**Issue by romangraef** [allrod5/injectable#37]
Current situation:
```py
T = TypeVar("T")

def inject(dependency: Union[T, str], ...) -> T
inject(A) # claims to return A not something of type A
```
Example:
![grafik](https://user-images.githubusercontent.com/20768569/87234505-d6599e00-c3d1-11ea-9c4a-22de2007d2d8.png)

Correct situation:
```py
T = TypeVar("T")

def inject(dependency: Union[Type[T], str], ...) -> T
inject(A) # now claims to return an instance of A
```

I'm not an expert when it comes to typing, but this is what i think causes it. Also maybe this is an issue with intellijs type system, but I don't have any other type checkers rn.

_By submiting an issue I accept this project's
[Code of Conduct](https://github.com/allrod5/injectable/blob/master/CODE_OF_CONDUCT.md). Any issue out of
these guidelines can be deleted at any moment without further explanation._

**Comment by allrod5** [comment]
Hi @romangraef, a fix for this bug was released in version 3.4.4 and it is already available at PyPI. Thanks for your help on this bug!
