### ISSUE TITLE
Autowiring should be done without actually importing the dependency's class

### ISSUE THREAD

**Issue by allrod5** [allrod5/injectable#6]
Autowiring should be able to resolve dependencies from a global scope without requiring the class specification:

This is how one would autowire today:
```python
# application.models.model.py
class Model:
    def __init__():
        self.foo = 'foo'

# application.services.service.py
class Service:
    def __init__():
        self.bar = 'bar'

# application.qux.qux.py
from injectable import autowired
from application.models.model import Model
from application.services.service import Service

class Qux:
    @autowired
    def __init__(self, *, model: Model, service: Service):
        self.model = model
        self.service = service
```

This is how it should be:
```python
# application.models.model.py
from injectable import injectable

class Model:
    @injectable
    def __init__():
        self.foo = 'foo'

# application.services.service.py
from injectable import injectable

class Service:
    @injectable
    def __init__():
        self.bar = 'bar'

# application.qux.qux.py
from injectable import autowired
from injectable import inject

class Qux:
    @autowired
    def __init__(self, *, model = inject('Model'), service = inject('Service')):
        self.model = model
        self.service = service
```

**Comment by FredrikWendt** [comment]
Wouldn't this make refactoring harder (changing class names that appears in strings)?

**Comment by allrod5** [comment]
@FredrikWendt yes indeed. I've been planning to enable contexts to better manage this and avoid this collateral issue. Contexts will be the major new feature in 3.0.0, I'll come up soon with details on how this will work.

For this issue, it will be closed and superseded by contexts in Injectable 3.0.0.

Thank you for the feedback :hearts:

**Comment by blackandred** [comment]
Sounds interesting.

**Comment by allrod5** [comment]
### Status Update

I've been planning to implement Contexts in similar manner to the way Profiles are implemented in Java Spring: each injectable dependency will be able to declare itself as injectable and specify a Context in which it will be available. To actually enable each dependency to declare itself available in a context without requiring a central point of the code to declare the context and assign all dependencies I've planned to enable automatic discovery and register of dependencies to contexts.

For that I've implemented a separate lib ([pycollect](https://github.com/allrod5/pycollect)) for directory traversal and collect of python files. It seems to work as expected though I'm yet to add a little more testing and documentation to it.

Soon I'll start experimenting with automatic dependency registering using [pycollect](https://github.com/allrod5/pycollect). This ideia was largely taken from how Apache Airflow "automagically" collects DAGs.

**Comment by allrod5** [comment]
This is now possible and totally optional by using qualifiers, which were introduced in the new 3.0.0 release.

@FredrikWendt @blackandred thank you for your contributions on this issue :hearts: Injectable 3.0.0 release matures this framework to provide first class dependency injection though it introduces little overhead over 2.x by requiring a call to `InjectionContainer.load()` at the start of the program among other little tweaks to functionality. If you find any issue or concern feel free to open a new issue!

Injectable now has an [official documentation](https://injectable.readthedocs.io/en/latest/) with [usage examples](https://injectable.readthedocs.io/en/latest/usage/index.html) and all (more polished examples are on the way too), please check it out too! :rocket:
