### ISSUE TITLE
Missing encoding in container injection

### ISSUE THREAD

**Issue by NoirPi** [allrod5/injectable#83]
Hey there, 
is there any reason for not having encoding in this line?

https://github.com/allrod5/injectable/blob/0e4516efd1f633103bac463e021d7b1415241cc8/injectable/container/injection_container.py#L173

maybe theres a easier solution then mine which was forking it and adding an encoding to that line.

`        with open(file_entry, encoding='utf-8') as file:`

this missing encoding caused me headaches so often now!

**Comment by NoirPi** [comment]
Closed due to:
#80 

awaiting merge

**Comment by allrod5** [comment]
Thanks for your report @NoirPi! I'll review the mentioned PR and most likely the fix will be released very soon.
